services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app:cached
      - /app/node_modules
    env_file:
      - ./backend/.env
  
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    depends_on:
      - backend

